name: 'golang-auto-test-example-ci'
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: print begin greet
        run: echo begin Github Action CI at `date`

      - name: checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: print env
        run: |
          pwd
          ls -l

      - name: set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12

      - name: go module
        run: |
          go mod tidy
          go mod verify

      - name: go lint
        run: |
          go get -u golang.org/x/lint/golint
          `go list -f {{.Target}} golang.org/x/lint/golint` ./...

      - name: run tests
        run: go test ./... -v -race -count=1 -cover

      - name: run benchmark
        run: |
          cd prd
          go test -v -bench=. -run=none -cpuprofile cpu.prof -memprofile mem.prof -count=1 -cover

      - name: print end greet
        run: echo end Github Action CI at `date`
